services:
  - type: web
    name: ai-image-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: TOGETHER_API_KEY
        sync: false